### PR TITLE
Icon Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icon is way off with the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#iconography) regarding icons. The point regarding highlight, shadows, pictogram, etc. Also, this one is more unique and aesthetically pleasing.

### CODE REVIEW

**Comment by rickybassom** [comment]
Thanks for your pull request! 

I like where this is going but unfortunately your icon doesn't fit well with my application's colour scheme. I have also just changed my icon since. If you redesign something along the same lines as my new icon that fits the eOS HIG I would likely accept it.

**Comment by Fatih20** [comment]
What's your color scheme? I use green because that's what green should be used for as said by James Blaede (The core elementary developer) on his [palette app](https://appcenter.elementary.io/com.github.cassidyjames.palette/). Maybe you should change the color scheme of your app as outlined in this palette app. It should be green instead of blue. Furthermore, the icon that you've designed doesn't deliver any meaning to the user as to what your app does. It's just a 3/4 circle, what's that supposed to mean?
You're welcome and sorry to be harsh, but this is a legitimate criticism I need to put forward.

**Comment by rickybassom** [comment]
I would not want to use a random colour like green just because it's part of the elementary colour scheme, I would rather use colours that remind people of the program.

Colour scheme from my code (colours part of the [colour scheme](https://elementary.io/docs/human-interface-guidelines#color)):
`pbar_progress_color = "#3689e6";`
`pbar_complete_color = "#c6262e";`

The 3/4 circle represents the recognisable progress bar used in my program (see screenshot). But a centred percentage sign could be added to convey more meaning. 

I made a quick rough edit on GIMP of what might be good:
image

**Comment by Fatih20** [comment]
Without the percent symbol in the middle, it has no meaning. That's what my problem was. Have you actually looked into the palette app and understand my argument about it?

**Comment by rickybassom** [comment]
Yes I have looked at the app and I do understand your argument. This isn't a strict guideline. I also don't understand why the grape colour was chosen if you are being strict to the rules.

Following the palette, blue is fine to use as an accent colour and is widely used throughout elementary os for its progress bars. I think that green doesn't work well as it conveys that a successful action has occurred when the bar represents progression.

I have expressed that adding the percentage sign would convey more meaning.

**Comment by Fatih20** [comment]
Alright, Ill get on it.

**Comment by Fatih20** [comment]
com github rickybas date-countdown
What do you think? Asking for opinion before I'm pixel fitting them.

**Comment by rickybassom** [comment]
Looks really good!

But feel that using the colour #3689e6 and maybe a very light grey in the centre might be a better fit. Could I see what it would look like with that colour scheme or I could try it myself if you send the .svg?

**Comment by Fatih20** [comment]
The center has a subtle gradient for skeuomorphic effect. What gradient do you think fit the center? Because what you've told me are solid color.

**Comment by rickybassom** [comment]
You can just use different brightness's of the same colour for the gradient. It's hard to see what would look good without testing them out myself.

**Comment by Fatih20** [comment]
https://drive.google.com/open?id=17cYRrv5zyp7f8SHON2vaEn1eeedX_frj You can look at it yourself.

**Comment by rickybassom** [comment]
Thoughts on these? I can't decide

test
test2
test3

**Comment by Fatih20** [comment]
None of the gradient that is used at the center circle expressed make the circle look skeuomorphic. To do this, the gradient should fulfill this 2 condition:

- Subtle enough that the object doesn't look its colored like a gradient
- Strong enough that it doesn't look like a flat color
- The darker color is at the opposite side of a supposed light source (in this case, top left corner).

I think you should've used lighter color for the arrow and darker one for the center circle.

**Comment by rickybassom** [comment]
Ok, should we go for the bottom one but with the centre gradient switched around?

**Comment by Fatih20** [comment]
Yes. Please show the result before merging them.

**Comment by rickybas** [comment]
Good to merge? Everything should be aligned also

**Comment by rickybassom** [comment]
What do you think? Should I merge it?

**Comment by Fatih20** [comment]
Have they been pixel fitted?

**Comment by rickybassom** [comment]
I wasn't going to but if you want to do it I would accept it.

**Comment by Fatih20** [comment]
Yes, I will. Wait for it.

**Comment by Fatih20** [comment]
Eh, you can just merge it.

**Pull request merged**
