### PR TITLE
Use elementary's template to test app

### PR DESCRIPTION
**Pull request by meisenzahl**

### CODE REVIEW

**Comment by NathanBnm** [comment]
Adding the travis.yml file is not enough. @rickybas you have to register in Travis CI too if you want to use Continuous Integration (highly recommended). See the wiki here https://github.com/elementary/houston/wiki/Continuous-Integration.

But it seems you're already use it but not correctly according to elementary. Please merge this if you want Houston CI to review pull requests.

**Review by NathanBnm — APPROVED** [review]

**Comment by rickybas** [comment]
Thanks @NathanBnm !

Sorry for the delay

**Comment by rickybassom** [comment]
Thanks for the contribution @meisenzahl !

**Comment by NathanBnm** [comment]
@rickybas don't forget to register on Travis CI in order to use continuous integration.

**Pull request merged**
